[package]
name = "rust_hypervisor"
version = "0.1.0"
authors = ["Siran Li <953760237@qq.com>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
volatile = "0.4.4"
spin = "0.9.0"
rlibc = "1.0.0"
register = "1.0.2"
cortex-a = "5.1.6"
buddy_system_allocator = "0.7.0"
fatfs = { version = "0.3.5", features = ["core_io", "alloc"], default-features = false }
core_io = "0.1"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]

[features]
tx2 = []
qemu = []