[package]
name = "rust_hypervisor"
version = "0.1.0"
authors = ["Siran Li <953760237@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
volatile = "0.2.6"
spin = "0.4.9"
rlibc = "1.0.0"
register = "0.5.0"
cortex-a = "5.1.6"
buddy_system_allocator = "0.7.0"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]
