[package]
name = "rust_hypervisor"
version = "0.1.0"
authors = ["Siran Li <953760237@qq.com>"]
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
debug = true


[dependencies]
vm-fdt = {path = "/home/ohmr/work/rust_projects/vm-fdt"}
fdt = {path = "/home/ohmr/work/rust_projects/libfdt-binding"}
log = "0.4.5"
volatile = "0.4.4"
spin = "0.9.0"
cortex-a = "6.1.0"
buddy_system_allocator = "0.8.0"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]

[dependencies.tock-registers]
version = "0.7.0"
default-features = false
features = ["register_types"]

[features]
tx2 = []
qemu = []

